/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Korisnik;
import java.util.logging.Level;
import java.util.logging.Logger;
import kont.Kontroler;

/**
 *
 * @author Dusan
 */
public class GlavnaForma extends javax.swing.JFrame {

    Korisnik korisnik;

    public GlavnaForma(Korisnik ulogovan) {
        initComponents();
        this.setTitle("Glavna forma");
        this.korisnik = ulogovan;
        labelaUlogovaniKorisnik.setText("Dobrodošli, " + korisnik.toString() + "!");
    }

    private GlavnaForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelaUlogovaniKorisnik = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mbObrisiLek = new javax.swing.JMenu();
        mnUnesiLek = new javax.swing.JMenuItem();
        mnObrisiLek = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnUnesiLekara = new javax.swing.JMenuItem();
        mnObrisiLekara = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnUnesiPacijenta = new javax.swing.JMenuItem();
        mtObrisiPacijenta = new javax.swing.JMenuItem();
        mnPretrazivanjePacijenta = new javax.swing.JMenuItem();
        mnIzmenaPacijenta = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnUnosTerapije = new javax.swing.JMenuItem();
        mnIzmenaTerapije = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnIzlogujSe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Uspesno logovanje");

        labelaUlogovaniKorisnik.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelaUlogovaniKorisnik.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelaUlogovaniKorisnik)
                    .addComponent(jLabel1))
                .addContainerGap(336, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(labelaUlogovaniKorisnik)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mbObrisiLek.setText("Lek");

        mnUnesiLek.setText("Unesi Lek");
        mnUnesiLek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUnesiLekActionPerformed(evt);
            }
        });
        mbObrisiLek.add(mnUnesiLek);

        mnObrisiLek.setText("Obrisi Lek");
        mnObrisiLek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnObrisiLekActionPerformed(evt);
            }
        });
        mbObrisiLek.add(mnObrisiLek);

        jMenuBar1.add(mbObrisiLek);

        jMenu2.setText("Lekar");

        mnUnesiLekara.setText("Unesi lekara");
        mnUnesiLekara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUnesiLekaraActionPerformed(evt);
            }
        });
        jMenu2.add(mnUnesiLekara);

        mnObrisiLekara.setText("Obrisi lekara");
        mnObrisiLekara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnObrisiLekaraActionPerformed(evt);
            }
        });
        jMenu2.add(mnObrisiLekara);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Pacijent");

        mnUnesiPacijenta.setText("Unesi pacijenta");
        mnUnesiPacijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUnesiPacijentaActionPerformed(evt);
            }
        });
        jMenu3.add(mnUnesiPacijenta);

        mtObrisiPacijenta.setText("Obrisi pacijenta");
        mtObrisiPacijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtObrisiPacijentaActionPerformed(evt);
            }
        });
        jMenu3.add(mtObrisiPacijenta);

        mnPretrazivanjePacijenta.setText("Pretrazivanje pacijenta");
        mnPretrazivanjePacijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPretrazivanjePacijentaActionPerformed(evt);
            }
        });
        jMenu3.add(mnPretrazivanjePacijenta);

        mnIzmenaPacijenta.setText("Izmena pacijenta");
        mnIzmenaPacijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIzmenaPacijentaActionPerformed(evt);
            }
        });
        jMenu3.add(mnIzmenaPacijenta);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Terapija");

        mnUnosTerapije.setText("Unos terapije");
        mnUnosTerapije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUnosTerapijeActionPerformed(evt);
            }
        });
        jMenu4.add(mnUnosTerapije);

        mnIzmenaTerapije.setText("Izmena terapije");
        mnIzmenaTerapije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIzmenaTerapijeActionPerformed(evt);
            }
        });
        jMenu4.add(mnIzmenaTerapije);

        jMenuBar1.add(jMenu4);

        jMenu1.setText("Korisnik");

        mnIzlogujSe.setText("Izloguj se");
        mnIzlogujSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIzlogujSeActionPerformed(evt);
            }
        });
        jMenu1.add(mnIzlogujSe);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnUnesiLekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUnesiLekActionPerformed
        UnosNovogLeka unk = new UnosNovogLeka();
        unk.setVisible(true);
    }//GEN-LAST:event_mnUnesiLekActionPerformed

    private void mnObrisiLekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnObrisiLekActionPerformed
        BrisanjeLeka bl = new BrisanjeLeka(this);
        bl.setVisible(true);
    }//GEN-LAST:event_mnObrisiLekActionPerformed

    private void mnUnesiLekaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUnesiLekaraActionPerformed
        UnosNovogLekara unlk = new UnosNovogLekara();
        unlk.setVisible(true);
    }//GEN-LAST:event_mnUnesiLekaraActionPerformed

    private void mnObrisiLekaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnObrisiLekaraActionPerformed
        BrisanjeLekara bl = new BrisanjeLekara(this);
        bl.setVisible(true);
    }//GEN-LAST:event_mnObrisiLekaraActionPerformed

    private void mnUnesiPacijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUnesiPacijentaActionPerformed
        UnosNovogPacijenta unp = new UnosNovogPacijenta(this);
        unp.setVisible(true);
    }//GEN-LAST:event_mnUnesiPacijentaActionPerformed

    private void mtObrisiPacijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtObrisiPacijentaActionPerformed
        try {
            PretragaPacijenta pp = new PretragaPacijenta(this);
            pp.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_mtObrisiPacijentaActionPerformed

    private void mnPretrazivanjePacijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPretrazivanjePacijentaActionPerformed
        try {
            PretragaPacijenta pp = new PretragaPacijenta(this);
            pp.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnPretrazivanjePacijentaActionPerformed

    private void mnIzmenaPacijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIzmenaPacijentaActionPerformed
        try {
            PretragaPacijenta pp = new PretragaPacijenta(this);
            pp.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnIzmenaPacijentaActionPerformed

    private void mnIzlogujSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIzlogujSeActionPerformed
        izlogujSe();
        this.dispose();
    }//GEN-LAST:event_mnIzlogujSeActionPerformed

    private void mnUnosTerapijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUnosTerapijeActionPerformed
        try {
            UnosTerapije ut = new UnosTerapije(this, korisnik);
            ut.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnUnosTerapijeActionPerformed

    private void mnIzmenaTerapijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIzmenaTerapijeActionPerformed
        try {
            PretragaTerapijeForma ptf = new PretragaTerapijeForma(this,korisnik);
            ptf.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnIzmenaTerapijeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelaUlogovaniKorisnik;
    private javax.swing.JMenu mbObrisiLek;
    private javax.swing.JMenuItem mnIzlogujSe;
    private javax.swing.JMenuItem mnIzmenaPacijenta;
    private javax.swing.JMenuItem mnIzmenaTerapije;
    private javax.swing.JMenuItem mnObrisiLek;
    private javax.swing.JMenuItem mnObrisiLekara;
    private javax.swing.JMenuItem mnPretrazivanjePacijenta;
    private javax.swing.JMenuItem mnUnesiLek;
    private javax.swing.JMenuItem mnUnesiLekara;
    private javax.swing.JMenuItem mnUnesiPacijenta;
    private javax.swing.JMenuItem mnUnosTerapije;
    private javax.swing.JMenuItem mtObrisiPacijenta;
    // End of variables declaration//GEN-END:variables

    private void izlogujSe() {
        try {
            Kontroler.vratiInstancu().izlogujKorisnika(korisnik);
        } catch (Exception ex) {
            Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void formWindowClosed(java.awt.event.WindowEvent evt) {
        izlogujSe();

    }

    private void formWindowClosing(java.awt.event.WindowEvent evt) {
        izlogujSe();
    }
}
